// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvpeiqoephkugoqecxxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cGVpcW9lcGhrdWdvcWVjeHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDE0NzAsImV4cCI6MjA2NjU3NzQ3MH0.N09Lu0t49Rt2oti8BJk37nt9-R4UM1XXzBKaON4BYNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);